let DATA=window.TRIP_DATA; const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function tabNav(){ $$(".nav button").forEach(b=>b.onclick=()=>{ $$(".nav button").forEach(x=>x.classList.remove("active")); b.classList.add("active"); $$(".section").forEach(s=>s.classList.remove("active")); $("#"+b.dataset.tab).classList.add("active"); if(b.dataset.tab==="mapa") setTimeout(()=>window.tripMap?.invalidateSize(),100); });}
function renderTrip(){const el=$("#timeline");DATA.trip.forEach(d=>{const e=document.createElement("div");e.className="card day";e.innerHTML=`<div class="date">${d.short}<small>${d.weekday}</small></div><div><h3>${d.title}</h3><div class="muted">${d.city}</div><div class="periods"><div class="period"><b>Manhã</b><ul>${d.morning.map(x=>`<li>${x}</li>`).join("")}</ul></div><div class="period"><b>Tarde</b><ul>${d.afternoon.map(x=>`<li>${x}</li>`).join("")}</ul></div><div class="period"><b>Noite</b><ul>${d.night.map(x=>`<li>${x}</li>`).join("")}</ul></div></div><p class="muted">${d.notes}</p></div><span class="tag ${d.status}">${d.status}</span>`;el.appendChild(e)})}
function placeFilters(){let cats=["Todos",...new Set(DATA.places.map(p=>p.category))],box=$("#filters");cats.forEach((c,i)=>{let b=document.createElement("button");b.textContent=c;b.className=i===0?"active":"";b.onclick=()=>{$$("#filters button").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderPlaces(c)};box.appendChild(b)})}
function renderPlaces(cat="Todos"){const el=$("#places");el.innerHTML="";DATA.places.filter(p=>cat==="Todos"||p.category===cat).forEach(p=>{let d=document.createElement("div");d.className="card place";d.innerHTML=`<div class="category">${p.category} · ${p.region}</div><h3>${p.name}</h3><div class="muted">${p.when}</div><p>${p.note}</p><div class="actions"><a target="_blank" class="btn maps" href="${p.maps}">Google Maps</a><a target="_blank" class="btn waze" href="${p.waze}">Waze</a></div>`;el.appendChild(d)})}
function renderMap(){const map=L.map('map').setView([38,-119],5);window.tripMap=map;L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap',maxZoom:19}).addTo(map);let pts=[];DATA.places.filter(p=>p.lat&&p.lon).forEach(p=>{L.marker([p.lat,p.lon]).addTo(map).bindPopup(`<b>${p.name}</b><br>${p.region}<br><a target="_blank" href="${p.maps}">Google Maps</a>`);pts.push([p.lat,p.lon])}); if(pts.length){L.polyline(pts,{weight:3,opacity:.55}).addTo(map);map.fitBounds(pts,{padding:[20,20]})}}
function renderReservations(){let e=$("#reservationsBody");DATA.reservations.forEach(r=>{e.innerHTML+=`<tr><td>${r.item}</td><td>${r.date}</td><td class="${r.status==='Pendente'?'statusPend':'statusOk'}">${r.status}</td><td>${r.action}</td></tr>`})}
function renderFood(){let e=$("#foodGrid");DATA.food.forEach(x=>e.innerHTML+=`<div class="card"><div class="muted">${x.region}</div><h3>🍽️ ${x.strategy}</h3><p>${x.details}</p></div>`)}
function renderFuel(){let e=$("#fuelGrid");DATA.fuel.forEach(x=>e.innerHTML+=`<div class="card"><div class="muted">${x.leg}</div><h3>⛽ ${x.stop}</h3><p><b>${x.rule}</b></p><p>${x.action}</p></div>`)}
function renderBudget(){let e=$("#budgetLines"),usd=0;DATA.budget.forEach(x=>{if(x.currency==="USD")usd+=x.base;e.innerHTML+=`<div class="budgetLine"><b>${x.item}</b><span>${x.currency} ${x.min}</span><span>${x.currency} ${x.base}</span><span>${x.currency} ${x.max}</span></div>`});$("#totalUsd").textContent=usd}
function renderChecklist(){let box=$("#checkGrid");DATA.checklist.forEach((g,gi)=>{let d=document.createElement("div");d.className="card checkGroup";d.innerHTML=`<h3>${g.group}</h3>`+g.items.map((x,i)=>{let id=`check_${gi}_${i}`;let checked=localStorage.getItem(id)==="1"?"checked":"";return `<label class="checkItem"><input id="${id}" type="checkbox" ${checked}><span>${x}</span></label>`}).join("");box.appendChild(d)}); $$('#checkGrid input').forEach(i=>i.onchange=()=>localStorage.setItem(i.id,i.checked?"1":"0"))}
function today(){let d=new Date(),fmt=new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Los_Angeles',day:'2-digit',month:'2-digit'}).format(d),t=DATA.trip.find(x=>x.short===fmt);$("#today").innerHTML=t?`<div class="eyebrow">Hoje</div><div class="big">${t.title}</div><p>${t.city}</p><p class="muted">${t.morning.slice(0,2).join(" · ")}</p>`:`<div class="eyebrow">Contagem regressiva</div><div class="big">Califórnia 2026 ✈️</div><p class="muted">O briefing automático entra em ação na viagem, às 07:00 local.</p>`}
renderTrip();placeFilters();renderPlaces();renderMap();renderReservations();renderFood();renderFuel();renderBudget();renderChecklist();today();tabNav();
if('serviceWorker' in navigator){addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}